/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 17 22:35:38 GMT 2019
 */

package org.jfree.chart.plot.dial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jfree.chart.plot.dial.DialLayer;
import org.jfree.chart.plot.dial.DialLayerChangeEvent;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class DialLayerChangeEvent_ESTest extends DialLayerChangeEvent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DialLayerChangeEvent dialLayerChangeEvent0 = null;
      try {
        dialLayerChangeEvent0 = new DialLayerChangeEvent((DialLayer) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // null source
         //
         verifyException("java.util.EventObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DialLayer dialLayer0 = mock(DialLayer.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(dialLayer0).toString();
      DialLayerChangeEvent dialLayerChangeEvent0 = new DialLayerChangeEvent(dialLayer0);
      DialLayer dialLayer1 = dialLayerChangeEvent0.getDialLayer();
      assertFalse(dialLayer1.isClippedToWindow());
  }
}
