/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 17 22:29:55 GMT 2019
 */

package org.jfree.chart.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.text.FieldPosition;
import java.text.ParsePosition;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.util.HexNumberFormat;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class HexNumberFormat_ESTest extends HexNumberFormat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HexNumberFormat hexNumberFormat0 = new HexNumberFormat(1);
      hexNumberFormat0.format(0L, (StringBuffer) null, (FieldPosition) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HexNumberFormat hexNumberFormat0 = new HexNumberFormat(0);
      hexNumberFormat0.getNumberOfDigits();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HexNumberFormat hexNumberFormat0 = new HexNumberFormat(1);
      hexNumberFormat0.setNumberOfDigits((-2663));
      hexNumberFormat0.getNumberOfDigits();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HexNumberFormat hexNumberFormat0 = new HexNumberFormat();
      FieldPosition fieldPosition0 = new FieldPosition((-2587));
      StringBuffer stringBuffer0 = hexNumberFormat0.format(1L, (StringBuffer) null, fieldPosition0);
      assertNotNull(stringBuffer0);
      assertEquals(10, stringBuffer0.length());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HexNumberFormat hexNumberFormat0 = new HexNumberFormat(0);
      FieldPosition fieldPosition0 = new FieldPosition(0);
      StringBuffer stringBuffer0 = hexNumberFormat0.format(0L, (StringBuffer) null, fieldPosition0);
      assertNotNull(stringBuffer0);
      assertEquals(0, hexNumberFormat0.getNumberOfDigits());
      assertEquals(3, stringBuffer0.length());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HexNumberFormat hexNumberFormat0 = new HexNumberFormat();
      FieldPosition fieldPosition0 = new FieldPosition((-2587));
      hexNumberFormat0.setNumberOfDigits((-2587));
      hexNumberFormat0.format((double) 1L, (StringBuffer) null, fieldPosition0);
      assertEquals((-2587), hexNumberFormat0.getNumberOfDigits());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      HexNumberFormat hexNumberFormat0 = new HexNumberFormat();
      ParsePosition parsePosition0 = new ParsePosition(4);
      hexNumberFormat0.parse("g", parsePosition0);
      assertEquals(8, hexNumberFormat0.getNumberOfDigits());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      HexNumberFormat hexNumberFormat0 = new HexNumberFormat();
      int int0 = hexNumberFormat0.getNumberOfDigits();
      assertEquals(8, int0);
  }
}
